{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "team6-helm.fullname" . }}-postgres-password
  labels:
    {{- include "team6-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ include "team6-helm.fullname" . }}-postgres-password
    creationPolicy: Owner
  data:
    - secretKey: PG_DSN
      remoteRef:
        key: /v1/kv/data/team6/postgres
        property: PG_DSN
{{- end }}