apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
spec:
  replicas: {{ .Values.main.replicas | default 1 }}
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service
          image: {{ .Values.main.image }}
          imagePullPolicy: {{ .Values.main.imagePullPolicy | default "IfNotPresent" }}
          command: [ "./main" ]
          ports:
            - containerPort: {{ .Values.main.port | default 5000 }}
          env:
            - name: HOST
              value: {{ .Values.main.host | default "main-service"  | quote}}
            - name: PORT
              value: {{ .Values.main.port | default "5000" | quote }}
            - name: TIMEOUT
              value: {{ .Values.main.timeout | default "30s" | quote }}
            - name: IDLE_TIMEOUT
              value: {{ .Values.main.idle_timeout | default "30s" | quote }}
            - name: STUDY_SERVICE_GRPC_HOST
              value: {{ .Values.main.study_service_host | default "study-service" | quote }}
            - name: STUDY_SERVICE_GRPC_PORT
              value: {{ .Values.main.study_service_port | default "5000" | quote }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.main.port | default 5000 }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.main.port | default 5000 }}
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: {{ .Values.main.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.main.port | default 5000 }}
      targetPort: {{ .Values.main.port | default 5000 }}
      {{- if eq (.Values.main.serviceType | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.main.nodePort | default 30084 }}
      {{- end }}
  selector:
    app: main-service