apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: {{ .Values.minio.replicas | default 1 }}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image | default "quay.io/minio/minio:latest" }}
          imagePullPolicy: {{ .Values.minio.imagePullPolicy | default "IfNotPresent" }}
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":{{ .Values.minio.consolePort | default 9090 }}"
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | default "minioadmin" }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.rootPassword | default "minioadmin" }}
          ports:
            - containerPort: {{ .Values.minio.apiPort | default 9000 }}
              name: api
            - containerPort: {{ .Values.minio.consolePort | default 9090 }}
              name: console
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: minio-data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: {{ .Values.minio.apiPort | default 9000 }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: {{ .Values.minio.apiPort | default 9000 }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ .Values.minio.pvcName | default "minio-pvc" }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: {{ .Values.minio.serviceType | default "ClusterIP" }}
  ports:
    - name: api
      port: {{ .Values.minio.apiPort | default 9000 }}
      targetPort: api
    - name: console
      port: {{ .Values.minio.consolePort | default 9090 }}
      targetPort: console
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.minio.pvcName | default "minio-pvc" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize | default "20Gi" }}
  {{- if .Values.minio.storageClassName }}
  storageClassName: {{ .Values.minio.storageClassName }}
  {{- end }}