apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  db-password: {{ .Values.postgresPassword | b64enc }}
  pg-dsn: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" .Values.global.postgres.user .Values.postgres.password .Values.global.postgres.host .Values.global.postgres.port .Values.global.postgres.database | b64enc }}
  minio-root-user: {{ .Values.minio.rootUser | b64enc }}
  minio-root-password: {{ .Values.minio.rootPassword | b64enc }}