apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.global.postgres.password }}
  db-password: {{ .Values.global.postgres.password | toString | b64enc }}
  {{- end }}

  {{- if and .Values.global.postgres.user .Values.global.postgres.password .Values.global.postgres.host .Values.global.postgres.port .Values.global.postgres.database }}
  pg-dsn: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable"
    (.Values.global.postgres.user | toString)
    (.Values.global.postgres.password | toString)
    (.Values.global.postgres.host | toString)
    (.Values.global.postgres.port | toString)
    (.Values.global.postgres.database | toString) | b64enc }}
  {{- end }}

  minio-root-user: {{ (.Values.minio.rootUser | default "minioadmin") | toString | b64enc }}
  minio-root-password: {{ (.Values.minio.rootPassword | default "minioadmin") | toString | b64enc }}