apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-service
spec:
  replicas: {{ .Values.study.replicas | default 1 }}
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
    spec:
      containers:
        - name: study-service
          image: {{ .Values.study.image }}
          imagePullPolicy: {{ .Values.study.imagePullPolicy | default "IfNotPresent" }}
          command: [ "./main" ]
          ports:
            - containerPort: {{ .Values.study.port | default 5000 }}
          env:
            - name: PG_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "team6-helm.fullname" . }}-postgres-secrets
                  key: PG_DSN

            - name: GRPC_HOST
              value: {{ .Values.study.host | quote }}
            - name: GRPC_PORT
              value: {{ .Values.study.port | quote }}

            # MinIO конфигурация
            - name: MINIO_HOST
              value: {{ .Values.global.minio.host | quote }}
            - name: MINIO_USE_SSL
              value: {{ .Values.global.minio.use_ssl | quote }}
            - name: MINIO_SERVER_URL
              value: {{ .Values.global.minio.server_url | quote }}
            - name: MINIO_REMOTE_URL
              value: {{ .Values.global.minio.remote_url | quote }}
            - name: MINIO_ROOT_USER
              value: {{ .Values.global.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.global.minio.rootPassword | quote }}

            # NATS
            - name: NATS_URI
              value: {{ .Values.global.nats.url | quote }}


          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.study.port | default 5000 }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.study.port | default 5000 }}
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: study-service
spec:
  type: {{ .Values.study.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.study.port | default 5000 }}
      targetPort: {{ .Values.study.port | default 5000 }}
      {{- if eq (.Values.study.serviceType | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.study.nodePort | default 30083 }}
      {{- end }}
  selector:
    app: study-service